services:
  ollama:
    gpus: all
    environment:
      "OLLAMA_KV_CACHE_TYPE": "q8_0"
      "OLLAMA_MAX_LOADED_MODELS": 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
