services:
  ollama:
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
    environment:
      "OLLAMA_KV_CACHE_TYPE": "q8_0"
      "OLLAMA_MAX_LOADED_MODELS": 1
